var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var strNumTuple;
var myVoid = undefined;
var myNull = undefined;
var myUndefined = undefined;
myString = 'hello this is omar!'.slice(1, 8);
myNum = 23;
myBool = false;
myVar = true;
strArr = ['hello', 'i am', 'omar'];
numArr = [1, 1, 2];
strNumTuple = ['Hello', 2];
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(strNumTuple);
